# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compare.Comparison')),
            ],
        ),
        migrations.CreateModel(
            name='Sentance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('origin', models.IntegerField(choices=[(1, 'Stjórnarskrá'), (2, 'Frumvarp')], default=1, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='comparison',
            name='frumvarp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frumvarp_set', to='compare.Sentance'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='stjornarskra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stjornarskra_set', to='compare.Sentance'),
        ),
        migrations.AddField(
            model_name='article',
            name='sentances',
            field=models.ManyToManyField(blank=True, to='compare.Sentance'),
        ),
    ]
