# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentance',
            name='origin',
            field=models.IntegerField(choices=[(1, 'Stjórnarskrá'), (2, 'Frumvarp')], default=1),
        ),
    ]
