# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20160809_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='nr',
        ),
        migrations.AddField(
            model_name='sentance',
            name='nr',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
