# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_auto_20160809_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentance',
            old_name='nr',
            new_name='article_nr',
        ),
    ]
