# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_auto_20160809_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=3)),
                ('sentances', models.ManyToManyField(to='compare.Sentance')),
            ],
        ),
    ]
