# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nr',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
