# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0009_sentance_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sentance',
            name='matches',
        ),
        migrations.AddField(
            model_name='match',
            name='sentance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Sentance'),
        ),
    ]
