# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0010_auto_20160809_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='frumvarp',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='stjornarskra',
        ),
        migrations.DeleteModel(
            name='Comparison',
        ),
    ]
