# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0011_auto_20160809_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sentance',
            new_name='Sentence',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sentances',
            new_name='sentences',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='sentance',
            new_name='sentence',
        ),
    ]
