# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0012_auto_20160809_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='sentence',
        ),
        migrations.AddField(
            model_name='match',
            name='frumvarp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='frumvarp', to='compare.Sentence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='stjornarskra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stjornarskra', to='compare.Sentence'),
            preserve_default=False,
        ),
    ]
